# Too spammy for us
comment: off

ignore:
  - "common/src/main/scala/net/psforever/objects/avatar/Avatars.scala"
  - "common/src/main/scala/net/psforever/objects/equipment/Ammo.scala"
  - "common/src/main/scala/net/psforever/objects/equipment/CItem.scala"
  - "common/src/main/scala/net/psforever/objects/equipment/EquipmentSize.scala"
  - "common/src/main/scala/net/psforever/objects/equipment/Kits.scala"
  - "common/src/main/scala/net/psforever/objects/equipment/SItem.scala"
  - "common/src/main/scala/net/psforever/objects/guid/AvailabilityPolicy.scala"
  - "common/src/main/scala/net/psforever/objects/vehicles/AccessPermissionGroup.scala"
  - "common/src/main/scala/net/psforever/objects/vehicles/SeatArmoRestriction.scala"
  - "common/src/main/scala/net/psforever/objects/vehicles/VehicleLockState.scala"
  - "common/src/main/scala/net/psforever/packet/crypto"
  - "common/src/main/scala/net/psforever/packet/game/objectcreate/DrawnSlot.scala"
  - "common/src/main/scala/net/psforever/packet/game/objectcreate/DriveState.scala"
  - "common/src/main/scala/net/psforever/packet/game/objectcreate/MountItem.scala"
  - "common/src/main/scala/net/psforever/packet/game/objectcreate/ObjectClass.scala"
  - "common/src/main/scala/net/psforever/packet/game/objectcreate/Prefab.scala"
  - "common/src/main/scala/net/psforever/packet/ControlPacketOpcode.scala"
  - "common/src/main/scala/net/psforever/packet/CryptoPacketOpcode.scala"
  - "common/src/main/scala/net/psforever/packet/GamePacketOpcode.scala"
  - "common/src/main/scala/net/psforever/objects/ObjectType.scala"
  - "common/src/main/scala/net/psforever/types/Angular.scala"
  - "common/src/main/scala/net/psforever/types/CertificationType.scala"
  - "common/src/main/scala/net/psforever/types/ChatMessageType.scala"
  - "common/src/main/scala/net/psforever/types/EmoteType.scala"
  - "common/src/main/scala/net/psforever/types/ExoSuitType.scala"
  - "common/src/main/scala/net/psforever/types/GrenadeState.scala"
  - "common/src/main/scala/net/psforever/types/ImplantType.scala"
  - "common/src/main/scala/net/psforever/types/MeritCommendation.scala"
  - "common/src/main/scala/net/psforever/types/PlanetSideEmpire.scala"
  - "common/src/main/scala/net/psforever/types/TransactionType.scala"
  - "pslogin/src/main/scala/services/avatar/AvatarAction.scala"
  - "pslogin/src/main/scala/services/avatar/AvatarResponse.scala"
  - "pslogin/src/main/scala/services/local/LocalAction.scala"
  - "pslogin/src/main/scala/services/local/LocalResponse.scala"
  - "pslogin/src/main/scala/services/vehicle/VehicleAction.scala"
  - "pslogin/src/main/scala/services/vehicle/VehicleResponse.scala"
  - "pslogin/src/main/scala/CryptoSessionActor.scala"
  - "pslogin/src/main/scala/DatabaseConnector.scala"
  - "pslogin/src/main/scala/LoginConfig.scala"
  - "pslogin/src/main/scala/Maps.scala"
  - "pslogin/src/main/scala/MDCContextAware.scala"
  - "pslogin/src/main/scala/MDCPropagatingExecutionContext.scala"
  - "pslogin/src/main/scala/Zones.scala"
