# Too spammy for us
comment: off

ignore:
  - "src/main/scala/net/psforever/objects/ObjectType.scala"
  - "src/main/scala/net/psforever/objects/avatar/Avatars.scala"
  - "src/main/scala/net/psforever/objects/ballistics/ProjectileResolution.scala"
  - "src/main/scala/net/psforever/objects/ballistics/Projectiles.scala"
  - "src/main/scala/net/psforever/objects/equipment/Ammo.scala"
  - "src/main/scala/net/psforever/objects/equipment/CItem.scala"
  - "src/main/scala/net/psforever/objects/equipment/EquipmentSize.scala"
  - "src/main/scala/net/psforever/objects/equipment/Kits.scala"
  - "src/main/scala/net/psforever/objects/equipment/SItem.scala"
  - "src/main/scala/net/psforever/objects/guid/AvailabilityPolicy.scala"
  - "src/main/scala/net/psforever/objects/serverobject/pad/AutoDriveControls.scala"
  - "src/main/scala/net/psforever/objects/serverobject/structures/StructureType.scala"
  - "src/main/scala/net/psforever/objects/serverobject/turret/TurretUpgrade.scala"
  - "src/main/scala/net/psforever/objects/serverobject/CommonMessages.scala"
  - "src/main/scala/net/psforever/objects/vehicles/AccessPermissionGroup.scala"
  - "src/main/scala/net/psforever/objects/vehicles/CargoVehicleRestiction.scala"
  - "src/main/scala/net/psforever/objects/vehicles/DestroyedVehicle.scala"
  - "src/main/scala/net/psforever/objects/vehicles/SeatArmoRestriction.scala"
  - "src/main/scala/net/psforever/objects/vehicles/Turrets.scala"
  - "src/main/scala/net/psforever/objects/vehicles/VehicleLockState.scala"
  - "src/main/scala/net/psforever/objects/vital/damage/DamageProfile.scala"
  - "src/main/scala/net/psforever/objects/vital/projectile/ProjectileCalculations.scala"
  - "src/main/scala/net/psforever/objects/vital/resistance/ResistanceProfile.scala"
  - "src/main/scala/net/psforever/objects/vital/DamageResistanceModel.scala"
  - "src/main/scala/net/psforever/objects/vital/DamageType.scala"
  - "src/main/scala/net/psforever/objects/vital/StandardDamages.scala"
  - "src/main/scala/net/psforever/objects/vital/StandardResistanceProfile.scala"
  - "src/main/scala/net/psforever/objects/vital/StandardResistances.scala"
  - "src/main/scala/net/psforever/objects/vital/StandardResolutions.scala"
  - "src/main/scala/net/psforever/packet/crypto"
  - "src/main/scala/net/psforever/packet/game/objectcreate/DrawnSlot.scala"
  - "src/main/scala/net/psforever/packet/game/objectcreate/DriveState.scala"
  - "src/main/scala/net/psforever/packet/game/objectcreate/MountItem.scala"
  - "src/main/scala/net/psforever/packet/game/objectcreate/ObjectClass.scala"
  - "src/main/scala/net/psforever/packet/game/objectcreate/Prefab.scala"
  - "src/main/scala/net/psforever/packet/ControlPacketOpcode.scala"
  - "src/main/scala/net/psforever/packet/CryptoPacketOpcode.scala"
  - "src/main/scala/net/psforever/packet/GamePacketOpcode.scala"
  - "src/main/scala/net/psforever/types/Angular.scala"
  - "src/main/scala/net/psforever/types/CertificationType.scala"
  - "src/main/scala/net/psforever/types/ChatMessageType.scala"
  - "src/main/scala/net/psforever/types/DriveState.scala"
  - "src/main/scala/net/psforever/types/EmoteType.scala"
  - "src/main/scala/net/psforever/types/ExoSuitType.scala"
  - "src/main/scala/net/psforever/types/GrenadeState.scala"
  - "src/main/scala/net/psforever/types/ImplantType.scala"
  - "src/main/scala/net/psforever/types/MeritCommendation.scala"
  - "src/main/scala/net/psforever/types/PlanetSideEmpire.scala"
  - "src/main/scala/net/psforever/types/TransactionType.scala"
  - "src/main/scala/net/psforever/services/avatar/AvatarAction.scala"
  - "src/main/scala/net/psforever/services/avatar/AvatarResponse.scala"
  - "src/main/scala/net/psforever/services/galaxy/GalaxyAction.scala"
  - "src/main/scala/net/psforever/services/galaxy/GalaxyResponse.scala"
  - "src/main/scala/net/psforever/services/local/LocalAction.scala"
  - "src/main/scala/net/psforever/services/local/LocalResponse.scala"
  - "src/main/scala/net/psforever/services/vehicle/VehicleAction.scala"
  - "src/main/scala/net/psforever/services/vehicle/VehicleResponse.scala"