services:
  loginserver:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-8u352-b08_1.8.3_2.13.10
    volumes:
      - .:/PSF-Loginserver:z
    working_dir: /PSF-Loginserver
    depends_on:
      - db
    ports:
      - 51000-51001:51000-51001/udp
      - 51002:51002/tcp
    command: sbt server/run
    environment:
      CONFIG_FORCE_database_host: db
      CONFIG_FORCE_bind: 0.0.0.0
  adminer:
    image: adminer
    ports:
      - 51010:8080
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: psforever
      POSTGRES_PASSWORD: psforever
      POSTGRES_DATABASE: psforever
