version: "3"
services:
  loginserver:
    image: mozilla/sbt
    volumes:
      - .:/PSF-Loginserver:z
    working_dir: /PSF-Loginserver
    depends_on:
      - db
    ports:
      - 51000-51001:51000-51001/udp
      - 51002:51002/tcp
    command: sbt server/run
  adminer:
    image: adminer
    ports:
      - 51010:8080
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: psforever
      POSTGRES_PASSWORD: psforever
      POSTGRES_DATABASE: psforever
